[package]
name = "bhuiz"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "vulkan_sdl"
required-features = ["vulkan", "sdl"]

[features]
vulkan = []
sdl = []

[dependencies]
# Internal
bhomz = { git = "https://github.com/bhuzgujj/bhomz.git", tag = "0.1.0" }

# Third party
log = "0.4.28"

[build-dependencies]
bindgen = "0.72.1"
