hard_tabs = true
single_line_let_else_max_width = 0
short_array_element_width_threshold = 0
match_block_trailing_comma = true
merge_derives = false
newline_style = "Unix"
style_edition = "2021"
use_field_init_shorthand = true
